services:
  - memcache
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - psql -c 'create database appfab_test;' -U postgres
  - cp config/database-travis.yml config/database.yml
  - rake db:migrate RAILS_ENV=test
rvm:
  - 2.0.0
env:
  - BUILD_TARGET=spec
  - BUILD_TARGET=cucumber
script: rake $BUILD_TARGET
